[logging]
version = 1

[logging.formatters.default]
format = "%(asctime)s %(levelname)-8s [%(filename)s:%(lineno)s] %(message)s"

[logging.loggers.app]
handlers = [ "service_file",]
level = "DEBUG"

[logging.handlers.service_file]
class = "logging.handlers.RotatingFileHandler"
filename = "/var/log/kreoshine/service.log"
maxBytes = 10485760
backupCount = 4
formatter = "default"
level = "DEBUG"
